version: "3"
services:
  web:
    build: ./gpt-server/
    ports:
      - "5000:5000"
    develop:
      watch:
        - action: sync
          path: ./gpt-server
          target: .
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    user: "redis:redis"
  postgres:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    user: "postgres:postgres"
